### ISSUE TITLE
Лабораторная 3 Вопросы

### ISSUE THREAD

**Issue by readysloth** [lex019020/ArhVS_labs#1]
Во втором задании программа свою задачу выполнила, но отработала некорректно (код возврата). Это потому что вы кое-что забыли сделать после вызова функции `printf`.
В третьем задании, похоже, та же ошибка.

-----
# [C (gcc)]

```C
    #include <stdio.h>
    
    int f2(){
      int a=1, b=2, c=3;
    }
    int f1(){
      int a, b, c;
      printf("%i %i %i", a, b, c);
    }
    int main()
    {
        f2();
        f1();
    }
```
[Try it online!][TIO-kgxrmyh2]

Код выше выводит `1 2 3` . Как думаете, почему?

[C (gcc)]: https://gcc.gnu.org/
[TIO-kgxrmyh2]: https://tio.run/##S9ZNT07@/185My85pzQlVcGmuCQlM18vw46LKzOvRCHNSEOzmktBAcROtDXUUUiyNdJRSLY1tuaqhSgwRFIAlAZKWgO5BUVAgTQNJdVMBTBS0oHJasJ05iZm5mlocoE0K4DtsYawDEGs2v//AQ "C (gcc) – Try It Online"

**Comment by lex019020** [comment]
Нужно было почистить стек и занулить регистр eax, из которого по умолчанию идёт возврат функции main.
![изображение](https://user-images.githubusercontent.com/59560888/101241366-647a4c00-3706-11eb-845b-5f94b2de0f74.png)
А у нас код выводит немного другие цифры)
![изображение](https://user-images.githubusercontent.com/59560888/101241460-36e1d280-3707-11eb-83fa-512d9bb46b4a.png)
Причина та же - цепляются мусорные данные из стека, т.к. отсутствует возврат значения из функций.

**Comment by readysloth** [comment]
Извините, проглядел второй скриншот....
В вашем случае выводятся другие цифры скорее всего из-за того, что у вас x64 система и используется соглашение о вызовах fastcall.
Предполагаю что троечка осталась в стеке как раз от вызова `f2`, а остальное -- некий мусор (`4200688` похож на адрес возврата)
