### ISSUE TITLE
Лабораторная 4 Вопросы

### ISSUE THREAD

**Issue by readysloth** [lex019020/ArhVS_labs#2]
+ Есть несколько способов поставить программную точку останова в C/C++ коде (аналогичную `pdb.set_trace()` в питоне). Как это будет записано с помощью ассемблерной вставки?
+ Каким образом (назовите хотя бы один) можно принудительно выставить флаги процессора в те значения, которые вы хотите

Ну и просто интересная ссылочка :)
https://habr.com/ru/post/520920/

**Comment by lex019020** [comment]
Для вызова точки останова можно использовать вставку, вызывающую сишную функцию raise с кодом SIGINT (Не работает в windows вроде)
![изображение](https://user-images.githubusercontent.com/59560888/101243069-c2129680-370e-11eb-9947-ec8e8275606d.png)
Либо более популярный и простой способ - ассемблерная функция int 3, вызывающая точку останова в дебаггере.
![изображение](https://user-images.githubusercontent.com/59560888/101243187-81674d00-370f-11eb-9505-812988fe075e.png)
Инстркуция int 3 считается сервисной и ловится дебаггером.

Выставлять флаги переполнения, прерывания и управления можно командами:
- clc, stc - установить в 0/1 флаг переполнения
- cli, sti - флаг прерывания
- cld, std - флаг управления

Для чтения и записи флагов знака, нуля, вспомогательного переноса, четности и переноса используют команды lahf и sahf, которые сохраняют значения флагов в регистр ah и загружают значения флагов из регистра ah соответственно.
